services:
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "8002:5002"
  
  poller:
    build:
      context: ./poller
      dockerfile: ../Dockerfile
    volumes:
      - ./poller:/app
    working_dir: /app
    ports:
      - "8001:5001"

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "8000:5000"
    
